name: Jutsu
author: ArcaneNetwork
api-version: 1.16
version: ${project.version}
main: com.jutsu.jutsu.Jutsu
softdepend: [GriefDefender, WorldGuard, WorldEdit, Factions, GriefPrevention, Towny, NoCheatPlus, LWC, Residence, Kingdoms, RedProtect, PlaceholderAPI, Lands]
commands:
  jutsu:
    usage: /<command>
permissions:
  jutsu.admin:
    default: op
    description: Grants access to all commands and abilities.
    children:
      jutsu.player: true
      jutsu.command.reload: true
      jutsu.admin.permaremove: true
      jutsu.command.add.others: true
      jutsu.command.add: true
      jutsu.command.rechoose: true
      jutsu.admin.choose: true
      jutsu.command.choose.ignorecooldown: true
      jutsu.ability.AvatarState: true
      jutsu.water.bloodbending.anytime: true
      jutsu.water.bloodbending: true
      jutsu.fire.bluefire: true
      jutsu.ability.Flight: true
      jutsu.ability.MetalClips.loot: true
      jutsu.ability.MetalClips.4clips: true
      jutsu.ability.MetalClips.throw: true
      jutsu.command.toggle.all: true
      jutsu.admin.toggle: true
      jutsu.command.invincible: true
      jutsu.command.check: true
      jutsu.command.preset.bind.assign: true
      jutsu.command.preset.bind.external: true
      jutsu.command.preset.bind.external.other: true
      jutsu.command.copy.assign: true
      jutsu.admin.debug: true
      jutsu.command.remove: true
  jutsu.player:
    default: true
    description: Grants access to most abilities and basic commands.
    children:
      jutsu.command.board: true
      jutsu.command.bind: true
      jutsu.command.display: true
      jutsu.command.toggle: true
      jutsu.command.copy: true
      jutsu.command.choose: true
      jutsu.command.version: true
      jutsu.command.help: true
      jutsu.command.clear: true
      jutsu.command.who: true
      jutsu.command.preset.list: true
      jutsu.command.preset.create.5: true
      jutsu.command.preset.create: true
      jutsu.command.preset.bind: true
      jutsu.command.preset.delete: true
      jutsu.air: true
      jutsu.water: true
      jutsu.earth: true
      jutsu.fire: true
      jutsu.chi: true
  jutsu.air:
    default: true
    description: Grants access to all airbending abilities.
    children:
      jutsu.command.add.air: true
      jutsu.command.choose.air: true
      jutsu.ability.AirBlast: true 
      jutsu.ability.AirBurst: true
      jutsu.ability.AirScooter: true
      jutsu.ability.AirShield: true
      jutsu.ability.AirSpout: true
      jutsu.ability.AirSuction: true
      jutsu.ability.AirSwipe: true
      jutsu.ability.Suffocate: true
      jutsu.ability.Tornado: true
      jutsu.ability.AirCombo: true
      jutsu.air.passive: true
      jutsu.air.flight: true
  jutsu.water:
    default: true
    description: Grants access to most waterbending abilities.
    children:
      jutsu.command.add.water: true
      jutsu.command.choose.water: true
      jutsu.ability.Bloodbending: true
      jutsu.ability.HealingWaters: true
      jutsu.ability.IceBlast: true
      jutsu.ability.IceSpike: true
      jutsu.ability.OctopusForm: true
      jutsu.ability.PhaseChange: true
      jutsu.ability.Surge: true
      jutsu.ability.Torrent: true
      jutsu.ability.WaterBubble: true
      jutsu.ability.WaterManipulation: true
      jutsu.ability.WaterSpout: true
      jutsu.ability.WaterSpout.Wave: true
      jutsu.ability.WaterCombo: true
      jutsu.water.plantbending: true
      jutsu.message.nightmessage: true
      jutsu.water.passive: true
      jutsu.water.icebending: true
      jutsu.water.healing: true
      jutsu.ability.WaterArms: true
      jutsu.ability.WaterArms.Pull: true
      jutsu.ability.WaterArms.Punch: true
      jutsu.ability.WaterArms.Grapple: true
      jutsu.ability.WaterArms.Grab: true
      jutsu.ability.WaterArms.Freeze: true
      jutsu.ability.WaterArms.Spear: true
      jutsu.ability.Bottlebending: true
  jutsu.earth:
    default: true
    description: Grants access to all Earthbending abilities.
    children:
      jutsu.command.add.earth: true
      jutsu.command.choose.earth: true
      jutsu.ability.Catapult: true
      jutsu.ability.Collapse: true
      jutsu.ability.EarthArmor: true
      jutsu.ability.EarthBlast: true
      jutsu.ability.EarthGrab: true
      jutsu.ability.EarthTunnel: true
      jutsu.ability.RaiseEarth: true
      jutsu.ability.Shockwave: true
      jutsu.ability.Tremorsense: true
      jutsu.ability.Extraction: true
      jutsu.ability.MetalClips: true
      jutsu.earth.passive: true
      jutsu.earth.metalbending: true
      jutsu.earth.lavabending: true
      jutsu.earth.sandbending: true
      jutsu.ability.LavaSurge: true
      jutsu.ability.LavaFlow: true
      jutsu.ability.EarthSmash: true
      jutsu.ability.SandSpout: true
      jutsu.ability.EarthCombo: true
  jutsu.fire:
    default: true
    description: Grants access to all firebending abilities.
    children:
      jutsu.command.add.fire: true
      jutsu.command.choose.fire: true
      jutsu.ability.Blaze: true
      jutsu.ability.FireBlast: true
      jutsu.ability.FireBurst: true
      jutsu.ability.FireJet: true
      jutsu.ability.FireShield: true
      jutsu.ability.HeatControl: true
      jutsu.ability.Illumination: true
      jutsu.ability.Lightning: true
      jutsu.ability.WallOfFire: true
      jutsu.ability.Combustion: true
      jutsu.ability.FireManipulation: true
      jutsu.ability.FireCombo: true
      jutsu.message.daymessage: true
      jutsu.fire.passive: true
      jutsu.fire.lightningbending: true
      jutsu.fire.combustionbending: true
  jutsu.chi:
    default: true
    description: Grants access to all ChiBlocking abilities.
    children:
      jutsu.command.add.chi: true
      jutsu.command.choose.chi: true
      jutsu.ability.HighJump: true
      jutsu.ability.Paralyze: true
      jutsu.ability.RapidPunch: true
      jutsu.ability.Smokescreen: true
      jutsu.ability.WarriorStance: true
      jutsu.ability.AcrobatStance: true
      jutsu.ability.QuickStrike: true
      jutsu.ability.SwiftKick: true
      jutsu.ability.ChiCombo: true
      jutsu.chi.passive: true
  jutsu.avatar:
    default: false
    description: Grants the Avatar Color.
  jutsu.ability.MetalClips.loot:
    default: false
    description: Lets a Metalbender loot a player's inventory of its iron.
  jutsu.ability.MetalClips.throw:
    default: false
    description: Lets a Metalbending throw a controlled entity.
  jutsu.ability.AirCombo:
    default: false
    description: Grants access to all AirCombos.
    children:
      jutsu.ability.AirSweep: true
      jutsu.ability.AirStream: true
      jutsu.ability.Twister: true
  jutsu.ability.Flight:
    default: false
    description: Grants access to Flight sub-abilities.
    children:
      jutsu.ability.Flight.Soar: true
      jutsu.ability.Flight.Glide: true
      jutsu.ability.Flight.Levitate: true
      jutsu.ability.Flight.Ending: true
  jutsu.ability.WaterCombo:
    default: false
    description: Grants access to all WaterCombos.
    children:
      jutsu.ability.IceWave: true
      jutsu.ability.IceBullet: true
      jutsu.ability.IceBulletLeftClick: true
      jutsu.ability.IceBulletRightClick: true
  jutsu.ability.EarthCombo:
    default: false
    description: Grants access to all EarthCombos.
    children:
      jutsu.ability.EarthPillars: true
      jutsu.ability.EarthDome: true
      jutsu.ability.EarthDomeOthers: true
  jutsu.ability.FireCombo:
    default: false
    description: Grants access to all FireCombos.
    children:
      jutsu.ability.FireKick: true
      jutsu.ability.FireSpin: true
      jutsu.ability.JetBlast: true
      jutsu.ability.JetBlaze: true
      jutsu.ability.FireWheel: true
  jutsu.ability.ChiCombo:
    default: false
    description: Grants access to all ChiCombos.
    children:
      jutsu.ability.Immobilize: true
  jutsu.air.passive:
    default:  false
    description: Grants access to all air passives.
    children:
      jutsu.ability.AirAgility: true
      jutsu.ability.AirSaturation: true
      jutsu.ability.GracefulDescent: true
  jutsu.chi.passive:
    default:  false
    description: Grants access to all chi passives.
    children:
      jutsu.ability.Acrobatics: true
      jutsu.ability.ChiAgility: true
      jutsu.ability.ChiSaturation: true
  jutsu.earth.passive:
    default:  false
    description: Grants access to all earth passives.
    children:
      jutsu.ability.DensityShift: true
      jutsu.ability.SandAgility: true
  jutsu.fire.passive:
    default:  false
    description: Grants access to all fire passives.
    children:
  jutsu.water.passive:
    default:  false
    description: Grants access to all water passives.
    children:
      jutsu.ability.FastSwim: true
      jutsu.ability.HydroSink: true
  jutsu.donor:
    default: false
    description: Grants the Donor tag.
